### ISSUE TITLE
Warning messages while running 

### ISSUE THREAD

**Issue by LeeNicha** [Russel88/CRISPRCasTyper#16]
Hi, I got warning messages while running this command
![Screen Shot 2564-08-13 at 13 46 34](https://user-images.githubusercontent.com/24719780/129316453-a1e1fdb2-5621-4839-85f7-e9312ef8b23a.png)

However, I got the results, but I'm not sure whether the warning from the program affects the results or not? 
![Screen Shot 2564-08-13 at 13 46 47](https://user-images.githubusercontent.com/24719780/129316649-97217c8c-8a75-4522-ba8e-95bae547c770.png)

Thank you in advance.

**Comment by Russel88** [comment]
Hi,

Thank you for reporting this!

First of all, it has no effects on the results.

It looks like pandas and xgboost have changed arguments for some of their functions, so I will fix this for the next version of cctyper, but you can simply ignore it.

It would be helpful if you could tell me what version of cctyper, pandas, and xgboost/py-xgboost you have installed in your conda environment.

- Jakob

**Comment by LeeNicha** [comment]
Thank you so much. 

cctyper v.1.4.4, pandas v1.3.0, py-xgboost v.1.4.0, python v3.9

I hope this information will help you.

**Comment by Russel88** [comment]
This is now fixed in version 1.5.0
