### ISSUE TITLE
About spacer sequences

### ISSUE THREAD

**Issue by wfgui** [Russel88/CRISPRCasTyper#18]
I use the the software to construct the CRISPRCas database from the bacterial genome in the Refseq database.
But I found that some spacer sequences are not in the genome，for example（spacers/NC_015711.1_1.fa）：`>NC_015711.1_1:1`
```
>NC_015711.1_1:1
TCAACCAGCATTAGCACCGTCCGCGTGGCGCCCGTGT
>NC_015711.1_1:2
CTGGAGTTGTCCCCCGAGGCTGAGCCGGTGTCCCGCGT
>NC_015711.1_1:3
TCTTCCATCTGCGTCTGCGTCTGACCCTTGAACTTCG
>NC_015711.1_1:4
ATGCAGAACAGCGGCAAGGAGGCGATTATCGACCT
>NC_015711.1_1:5
GGGCAGTGAAACCCTTGGGTGGGGAAGGAGTTCTGGGGGC
>NC_015711.1_1:6
AGGAGCGCCCGCCGGCCAGACGCATAGACGACGCA
```

Am i missing something？

Thanks！

[GCF_000219105.zip](https://github.com/Russel88/CRISPRCasTyper/files/7683281/GCF_000219105.zip)

**Comment by Russel88** [comment]
Dear wfgui,

Not sure what the problem is here. When I blast these 6 spacer sequences against NC_015711.1 I find perfect matches for all, as expected. 

See attached BLASTn table:
[BLASTn-Alignment.txt](https://github.com/Russel88/CRISPRCasTyper/files/7683697/BLASTn-Alignment.txt)

Cheers,
Jakob
