### ISSUE TITLE
Question about spacer direction

### ISSUE THREAD

**Issue by Dfvandenberg** [Russel88/CRISPRCasTyper#19]
Dear Russel,

are the spacers correction for their orientation like CRISPRDetect/CRISPRDirection does?

With kind regards,
Daan

**Comment by Russel88** [comment]
Dear Daan,

This is currently not implemented, but we are working on adding this as an extension. 
However, I will also point you to this paper (https://doi.org/10.3389/fmicb.2019.02054), which suggests that the orientation most of the time matches with the orientation of the associated _cas_ genes. In the cctyper output you can find the direction of the interference and adaptation modules. However, this criteria can obviously not be used for orphan arrays.

Best,
Jakob

**Comment by Dfvandenberg** [comment]
Dear Jakob,

thank you for your response!
I will read it.

with kind regards,
Daan
