### ISSUE TITLE
Cas6 in red in visualization?

### ISSUE THREAD

**Issue by mhyleung** [Russel88/CRISPRCasTyper#20]
Dear all

Why is it that the Cas6 proteins are coloured in red in the visualization, as opposed to the other enzymes of either adaptation (blue) or interference (red) modules? Is there something functionally unique about Cas6 to be coloured separately?

Thanks

Marcus

**Comment by Russel88** [comment]
Hi Marcus,

We chose to color Cas6 differently, as it is the enzyme responsible for processing pre-crRNA into mature, functional crRNA in Class 1 systems - sometimes forming part of the interference complex itself and othertimes not. There are of course exceptions, for example with I-C where Cas5d is responsible for crRNA maturation. 

https://www.nature.com/articles/nrmicro3569/figures/1
