### ISSUE TITLE
Problems running the program

### ISSUE THREAD

**Issue by JavierFFavieres** [Russel88/CRISPRCasTyper#24]
First of all I have to say the program is great. Easy to use and the output is very comprehensive. 
However, recently I have been having this error:

/Users/JFF/opt/miniconda3/envs/cctyper/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
[2022-04-04 14:29:15] INFO: Running CRISPRCasTyper version 1.3.0
[2022-04-04 14:29:15] INFO: Predicting ORFs with prodigal
[2022-04-04 14:29:15] INFO: Running HMMER against Cas profiles
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 691/691 [00:14<00:00, 48.44it/s]
[2022-04-04 14:29:31] INFO: Parsing HMMER output
[2022-04-04 14:29:31] INFO: Subtyping putative operons
/Users/JFF/opt/miniconda3/envs/cctyper/lib/python3.9/site-packages/cctyper/castyping.py:294: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  single_effector_hmms = self.scores[self.scores['Hmm'].isin(list(specifics))].drop('Hmm', 1)
[2022-04-04 14:29:31] INFO: Predicting CRISPR arrays with minced
[2022-04-04 14:29:31] INFO: No CRISPRs found.
[2022-04-04 14:29:31] INFO: Plotting map of CRISPR-Cas loci
[2022-04-04 14:29:31] INFO: Removing temporary files

It's strange because I have run this same sequence on other occasions with the program and I am sure there are CRISPRs. 
Do you know what might be causing this?

Kind regards,
Javier

**Comment by Russel88** [comment]
Dear Javier

There should not be differences between runs of the same cctyper versions. 
Could you have run it with another version of cctyper? I can see you're using an older CCTyper version.

Also, CRISPR arrays or cas operons that are different between occasions?

Best,
Jakob

**Comment by JavierFFavieres** [comment]
Thank you, updating the program did the trick. I still get the message "FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead" but the program works without issue.

Best,
Javier

**Comment by Russel88** [comment]
Great. Thank you for reporting this.

- Jakob
