### ISSUE TITLE
add repeated sequence to repeats.fa

### ISSUE THREAD

**Issue by fabgenomics** [Russel88/CRISPRCasTyper#25]
Hi,
I wanted to use your program to get E. coli spacers. It work well on some of my strains but for some of them there are missing spacers due to some mismatch in the last repeat sequence.
Is there a way to update the repeats.fa file in the db folder with my own list of repeated sequences ?
Have a nice day,
Fabien

**Comment by Russel88** [comment]
Hi Fabien,

Yes you can. If you use conda you can find the db directory inside the conda environment. Then you simply add your repeats to the repeats.fa file (give them unique names, not overlapping with any of the other names). When you run cctyper with the conda environment it will then use the updated file.

However, the repeats.fa is only used if minced is not finding a CRISPR array near a cas operon. Therefore, it will most likely not make any difference for you
