### ISSUE TITLE
Expose minced options

### ISSUE THREAD

**Issue by jimmyliu1326** [Russel88/CRISPRCasTyper#26]
Hello,

Is it possible to make the `minced` options available when calling `cctyper` ? Options like `-minNR`, `-minRL`, etc. are very useful when it comes to optimizing CRISPR array annotations. I have noticed that certain repeats are missed because the array did not carry the minimum number of repeats required.

Cheers,
Jimmy

**Comment by Russel88** [comment]
Hi Jimmy,

Good idea. I have now included that option in the new version 1.6.3. It is not on conda yet, but if you have cctyper 1.6.2 installed via conda, you can run the following in your conda env to upgrade to 1.6.3:
`python -m pip install cctyper --upgrade`

Cheers,
Jakob
