### ISSUE TITLE
No database with conda install?

### ISSUE THREAD

**Issue by nicholascdove** [Russel88/CRISPRCasTyper#29]
Hello, I installed cctyper with conda, 
`conda create -n cctyper -c conda-forge -c bioconda -c russel88 cctyper`
activated the environment,
`conda activate cctyper`
and then tried to run cctyper
`cctyper ~/Downloads/44_contigs_1000.fasta ~/Desktop/cctyper_output_44 --prodigal meta`

However, it says that it cannot find the database directory. Is there an easy way to fix this?

> [2022-08-03 13:40:32] INFO: Running CRISPRCasTyper version 1.3.0
>[2022-08-03 13:40:32] ERROR: Could not find database directory

Thanks,

Nicholas

**Comment by Russel88** [comment]
Hi Nicholas,

The quick fix is the set the CCTYPER_DB shell variable to the path where the database is located. This should normally happen automatically, though.
`export CCTYPER_DB="/path/to/conda/envs/cctyper/db`

If the database isn't downloaded, for some reason, you can see here how to downlaod it manually:
https://github.com/Russel88/CRISPRCasTyper#when-installing-with-pip-you-need-to-download-the-database-manually

By the way, I can see you are using an old version of CCTyper. It might also help to recreate the conda env with the newest version (1.6.4).

Cheers,
Jakob

**Comment by nicholascdove** [comment]
The quick fix did it! Thanks!
