### ISSUE TITLE
FileNotFoundError: blast.tab

### ISSUE THREAD

**Issue by TianyiChang** [Russel88/CRISPRCasTyper#30]
Hi there

I was wondering if you know what caused this issue, "FileNotFoundError: [Errno 2] No such file or directory: DIR/blast.tab"?

Thanks!

**Comment by Russel88** [comment]
Hi TianyiChang

It looks like a bug that appears when no repeat matches any sequences in the input. You can get around it by adding the --skip_blast argument when running cctyper. I will fix it in the next version.

Thank you for reporting!

**Comment by TianyiChang** [comment]
I see. Thanks a lot!
  
​

**Comment by Russel88** [comment]
Hi TianyiChang

I cannot reproduce that error. On my system a blast.tab file is always produced, even without matches.
Can you provide information on the version of cctyper and dependecies, and maybe a small example file which produce an error

Best,
Jakob
