### ISSUE TITLE
Complete genome and draft genome

### ISSUE THREAD

**Issue by illusion-a** [Russel88/CRISPRCasTyper#31]
Hello, I am going to use this software to predict some Klebsiella pneumoniae genome data (some are fully assembled genome data, some are draft genome data at the Scaffolds level).  Should I change the Prodigal Mode to make the prediction more accurate for different genomes? 
Complete genome: cctyper KP1.fa my_output
A draft genome containing multiple sequences(scaffolds): cctyper KP2.fasta my_output2 --prodigal meta
Are these commands correct?
If I keep using a command without changing it, will the result be much less reliable ?
Best wishes！

**Comment by Russel88** [comment]
Hi
The default mode is best for when the input fasta contains a single genome, no matter if it's complete or draft. Prodigal meta mode is only for short sequences or fasta files with contigs from different bacteria (e.g. metagenomes). So it sounds like you should just use default mode: cctyper genome.fa my_output.
Cheers,
Jakob

**Comment by illusion-a** [comment]
> 

I see. Thank you very much!
