### ISSUE TITLE
Different results from CRISPR Cas typer web server and standalone version

### ISSUE THREAD

**Issue by Smiriti-Gupta** [Russel88/CRISPRCasTyper#34]

**Comment by Russel88** [comment]
I need a bit more information to figure out where the problem could be.
* Are you using the same standalone version as what is run on the webserver?
* In which way are the results different?
* Do you have a reproducible example I can use for testing?

**Comment by Smiriti-Gupta** [comment]
Hello Sir,
Thank You for the response. Yes, I am using the same standalone version as
what is run on the web server (version 1.8.0). I am using this tool to
identify CRISPR-Cas systems in Metagenome Assembled Genomes (MAGs).The tool
identifies CRISPR-Cas systems in a particular bin through web server but no
CRISPR-Cas are identified for the same bin using the standalone version.
I also have certain other queries mentioned below:
1. How can we use the standalone version to identify CRISPR-Cas system from
all the bins at once.
2.Some of the Cas9 are predicted as ambiguous and the best type is shown as
Type II-A and Type II-C, what does this mean?
3.The predicted Cas operon tab has a false positive column but then also it
predicts the type and other details. Why?
4. What does unknown gene actually mean (the gene is not known to play a
role in CRISPR-Cas system or the function of the gene is not at all known)?
5. One of the contigs shows two Cas9 (adjacent to each other). What does it
signify?
6. Cas1 gene is mostly shown by purple color in the graph plot, but it is a
gene involved in adaptation so it should be shown in blue. What is the
reason for this?

I will be greatful for a quick response.
Thank You
Smiriti Gupta

**Comment by Russel88** [comment]
Hi
I will answer point by point. As for the difference between web server and standalone, how specifically are the outputs different? Do you use some non-default parameters on either the standalone or webserver?

1) You could put them all in one fasta and run cctyper with `--prodigal meta`, but it's faster to parallelize across MAGs with for example GNU parallel
2) There is a Cas9 HMM that matches both II-A and II-C, hence it's ambiguous
3) Not sure what you mean by a false positive column?
4) Unknown gene means that it is not CRISPR-Cas related
5) It's an operon with two cas9, or maybe it should have been one gene but the ORF was called wrongly
6) That sounds like a mistake, could you send one of the figures? Also, is it only for specific subtypes or for different subtypes?

Cheers,
Jakob

**Comment by Smiriti-Gupta** [comment]
![image](https://user-images.githubusercontent.com/121949837/212599561-d771b233-4bde-4850-8e5f-98a4164f78cb.png)
Please find the image showing Cas1 in purple. It is for all subtypes

**Comment by Russel88** [comment]
The Cas1 gene has the expected color. All adaptation related genes will have this color (blur, purple, or what you want to call it).
