### ISSUE TITLE
Orphan CRISPR definition

### ISSUE THREAD

**Issue by bio-unach** [Russel88/CRISPRCasTyper#44]
Dear Russel,

Thank you very much for this unique tool.

I have a simple question. How is defined an orphan CRISPR? I suppose that a lonely CRISPR in a contig could be considered an orphan, but how many ORFs are needed for considering an array as an orphan CRISPR?

**Comment by Russel88** [comment]
Hi
An orphan CRISPR is simply a CRISPR array that is not near a cas operon. The definition of "near" can be changed when running cctyper and is by default 10 kbp

**Comment by bio-unach** [comment]
Thank you very much!
