### ISSUE TITLE
(Question) How can I plot svg post-hoc after a run? 

### ISSUE THREAD

**Issue by jolespin** [Russel88/CRISPRCasTyper#49]
I just ran this on about 60k genomes before I realized the Drawsvg version made changes that weren't address in the current CCTyper implementation (see https://github.com/Russel88/CRISPRCasTyper/issues/45).  

Is there a way I can load the data that ran correctly so I can still plot it using CCTyper?

**Comment by Russel88** [comment]
You can run with the --redo_typying argument. Then at least prodigal and HMMER will not be run again
